export const SUBMIT_SIGNUP = "SUBMIT_SIGNUP";
export const FAILED_SIGNUP = "FAILED_SIGNUP";
export const SUCCESS_SIGNUP = "SUCCESS_SIGNUP";

export const ACTIVE_CODE_REQUEST = "ACTIVE_CODE_REQUEST";
export const ACTIVE_CODE_SUCCESS = "ACTIVE_CODE_SUCCESS";
export const ACTIVE_CODE_FAILED = "ACTIVE_CODE_FAILED";

export const SIGN_IN_REQUEST = "SIGN_IN_REQUEST";
export const SIGN_IN_SUCCESS = "SIGN_IN_SUCCESS";
export const SIGN_IN_FAILED = "SIGN_IN_FAILED";

export const GET_PROFILE_INFO_REQUEST = "GET_PROFILE_INFO_REQUEST";
export const GET_PROFILE_INFO_SUCCESS = "GET_PROFILE_INFO_SUCCESS";
export const GET_PROFILE_INFO_FAILED = "GET_PROFILE_INFO_FAILED";
